# Generated by Django 4.1.3 on 2022-11-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
    ]
