# Generated by Django 4.1.3 on 2022-11-19 21:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rename_matches_match'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authtoken',
            new_name='UserExtension',
        ),
    ]
