# Generated by Django 4.1.3 on 2022-11-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_authtoken_userextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='kontostand',
            field=models.FloatField(default=10000),
        ),
    ]
