# Generated by Django 4.1.3 on 2022-11-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userextension_kontostand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='kontostand',
            field=models.IntegerField(default=10000),
        ),
    ]
