# Generated by Django 4.1.3 on 2022-11-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_price_alter_order_quantity'),
        ('core', '0009_match_user_buyer_match_user_seller'),
    ]

    operations = [
    ]
