# Generated by Django 4.1.3 on 2022-11-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20221120_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
